export const contriCases = [
    {
        "casename": "case 15",
        "priority": "Medium",
        "type": "General",
        "status": "Open",
        "opendate": "2024-12-05",
        "co2": 14.29,
        "h2o": 28.57,
        "o2": 42.86,
        "n2": 14.29,
        "statuskey": "success",
        "contributing": "contributing"
    },
    {
        "casename": "case 7",
        "priority": "High",
        "type": "General",
        "status": "Open",
        "opendate": "2024-12-25",
        "co2": 26.09,
        "h2o": 45.65,
        "o2": 23.91,
        "n2": 4.35,
        "statuskey": "success",
        "contributing": "contributing"
    },
    {
        "casename": "xyz",
        "priority": "High",
        "type": "General",
        "status": "Closed",
        "opendate": "2024-12-25",
        "co2": 10,
        "h2o": 20,
        "o2": 1,
        "n2": 1,
        "statuskey": "neutral",
        "contributing": "contributing"
    },
    {
        "casename": "case 10",
        "priority": "Low",
        "type": "General",
        "status": "Closed",
        "opendate": "2025-01-03",
        "co2": 1,
        "h2o": 2,
        "o2": 4,
        "n2": 90,
        "statuskey": "neutral",
        "contributing": "contributing"
    },
    {
        "casename": "case 9",
        "priority": "Low",
        "type": "General",
        "status": "Open",
        "opendate": "2024-12-10",
        "co2": 25,
        "h2o": 37.5,
        "o2": 2,
        "n2": 9,
        "statuskey": "success",
        "contributing": "contributing"
    },
    {
        "casename": "case 4",
        "priority": "Low",
        "type": "General",
        "status": "Open",
        "opendate": "2024-12-04",
        "co2": 25,
        "h2o": 37.5,
        "o2": 12.5,
        "n2": 25,
        "statuskey": "success",
        "contributing": "contributing"
    },
    {
        "casename": "case 3",
        "priority": "High",
        "type": "General",
        "status": "Closed",
        "opendate": "2024-12-02",
        "co2": 14.29,
        "h2o": 28.57,
        "o2": 42.86,
        "n2": 14.29,
        "statuskey": "neutral",
        "contributing": "contributing"
    },
    {
        "casename": "case 2",
        "priority": "Medium",
        "type": "General",
        "status": "Open",
        "opendate": "2024-12-02",
        "co2": 4.17,
        "h2o": 87.5,
        "o2": 7,
        "n2": 4.17,
        "statuskey": "success",
        "contributing": "contributing"
    }
]